=== Foltrex/XML/src/main/resources/medicationsSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.epamcourses.by/medicins"
           xmlns:tns="http://www.epamcourses.by/medicins"
           elementFormDefault="qualified">

    <element name="medicine" type="tns:medicine" abstract="true"/>
    <element name="heart-medicine" type="tns:heart-medicine" substitutionGroup="tns:medicine"/>
    <element name="vascular-medicine" type="tns:vascular-medicine" substitutionGroup="tns:medicine"/>

    <element name="medicins">
        <complexType>
            <sequence>
                <element ref="tns:medicine" minOccurs="2" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="medicine">
        <sequence>
            <element name="name" type="string"/>
            <element name="group" type="string"/>
            <element name="analogs" type="tns:analogs"/>
            <element name="versions" type="tns:versions"/>
        </sequence>

        <attribute name="id" type="tns:medicine-id" use="required"/>
    </complexType>

    <complexType name="heart-medicine">
        <complexContent>
            <extension base="tns:medicine"/>
        </complexContent>
    </complexType>

    <complexType name="vascular-medicine">
        <complexContent>
            <extension base="tns:medicine"/>
        </complexContent>
    </complexType>

    <simpleType name="medicine-id">
        <restriction base="ID">
            <pattern value="\w{8,20}"/>
        </restriction>
    </simpleType>

    <complexType name="analogs">
        <sequence>
            <element name="analog" type="string" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="versions">
        <sequence>
            <element name="version" type="tns:version" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="version">
        <sequence>
            <element name="certificate" type="tns:certificate"/>
            <element name="package" type="tns:package"/>
            <element name="dosage" type="tns:dosage"/>
        </sequence>

        <attribute name="version-name" type="tns:version-name" use="required"/>
    </complexType>

    <simpleType name="version-name">
        <restriction base="string">
            <enumeration value="PILLS"/>
            <enumeration value="CAPSULES"/>
            <enumeration value="POWDER"/>
            <enumeration value="DROPS"/>
            <enumeration value="SOLUTION"/>
        </restriction>
    </simpleType>

    <complexType name="certificate">
        <sequence>
            <element name="issue-date" type="date"/>
            <element name="expiry-date" type="date"/>
        </sequence>

        <attribute name="number" type="tns:medicine-id" use="required"/>
        <attribute name="registering-organization" type="string" use="optional" default="lekpharm"/>
    </complexType>

    <complexType name="dosage">
        <sequence>
            <element name="dose" type="positiveInteger"/>
            <element name="medication-interval" type="tns:medication-interval"/>
        </sequence>
    </complexType>
    
    <simpleType name="medication-interval">
        <restriction base="string">
            <enumeration value="6 HOURS"/>
            <enumeration value="12 HOURS"/>
            <enumeration value="24 HOURS"/>
        </restriction>
    </simpleType>
    
    <complexType name="package">
        <sequence>
            <element name="type" type="tns:package-type"/>
            <element name="capacity" type="positiveInteger"/>
            <element name="price" type="positiveInteger"/>
        </sequence>
    </complexType>

    <simpleType name="package-type">
        <restriction base="string">
            <enumeration value="CARDBOARD BOX"/>
            <enumeration value="BLISTER"/>
            <enumeration value="BOTTLE"/>
        </restriction>
    </simpleType>
</schema>

=== Foltrex/XML/src/main/resources/medicins.xml
<?xml version="1.0" encoding="UTF-8"?>
<medicins xmlns="http://www.epamcourses.by/medicins"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.epamcourses.by/medicins  medicationsSchema.xsd ">

    <heart-medicine id="medicine290">
        <name>bisoprolol</name>
        <group>beta-blocant</group>
        <analogs>
            <analog>concor</analog>
            <analog>bicard</analog>
        </analogs>
        <versions>
            <version version-name="PILLS">
                <certificate number="N83bs90vb32" registering-organization="rapharm">
                    <issue-date>2021-12-05</issue-date>
                    <expiry-date>2023-12-05</expiry-date>
                </certificate>
                <package>
                    <type>CARDBOARD BOX</type>
                    <capacity>28</capacity>
                    <price>16</price>
                </package>
                <dosage>
                    <dose>5</dose>
                    <medication-interval>12 HOURS</medication-interval>
                </dosage>
            </version>
        </versions>
    </heart-medicine>

    <vascular-medicine id="medicine902">
        <name>piracetam</name>
        <group>nootropics</group>
        <analogs>
            <analog>lucetam</analog>
            <analog>macsotropil</analog>
        </analogs>
        <versions>
            <version version-name="CAPSULES">
                <certificate number="bUI82kd5ti">
                    <issue-date>2021-12-07</issue-date>
                    <expiry-date>2023-12-07</expiry-date>
                </certificate>
                <package>
                    <type>BLISTER</type>
                    <capacity>10</capacity>
                    <price>7</price>
                </package>
                <dosage>
                    <dose>400</dose>
                    <medication-interval>6 HOURS</medication-interval>
                </dosage>
            </version>
            <version version-name="SOLUTION">
                <certificate number="T9nkjSn93">
                    <issue-date>2021-11-17</issue-date>
                    <expiry-date>2023-11-17</expiry-date>
                </certificate>
                <package>
                    <type>BOTTLE</type>
                    <capacity>120</capacity>
                    <price>8</price>
                </package>
                <dosage>
                    <dose>2333</dose>
                    <medication-interval>6 HOURS</medication-interval>
                </dosage>
            </version>
            <version version-name="PILLS">
                <certificate number="BI1bksJHI">
                    <issue-date>2021-10-27</issue-date>
                    <expiry-date>2023-10-27</expiry-date>
                </certificate>
                <package>
                    <type>CARDBOARD BOX</type>
                    <capacity>10</capacity>
                    <price>10</price>
                </package>
                <dosage>
                    <dose>200</dose>
                    <medication-interval>6 HOURS</medication-interval>
                </dosage>
            </version>
        </versions>
    </vascular-medicine>
</medicins>

=== Foltrex/XML/src/test/resources/invalidMedicins.xml
<?xml version="1.0" encoding="UTF-8"?>
<medicins xmlns="http://www.epamcourses.by/medicins"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.epamcourses.by/medicins  medicationsSchema.xsd ">

    <heart-medicine id="medicin!!!!!e290">
        <name>bisoprolol</name>
        <group>beta-blocant</group>
        <analogs>
            <analog>concor</analog>
            <analog>bicard</analog>
        </analogs>
        <versions>
            <version version-name="PILLS">
                <certificate number="N83bs9!!!!!!0vb32" registering-organization="rapharm">
                    <issue-date>2021-12-05</issue-date>
                    <expiry-date>2023-12-05</expiry-date>
                </certificate>
                <package>
                    <type>CARDBOARD BOX</type>
                    <capacity>-28</capacity>
                    <price>-16</price>
                </package>
                <dosage>
                    <dose>5</dose>
                    <medication-interval>12 HOURS</medication-interval>
                </dosage>
            </version>
        </versions>
    </heart-medicine>

    <!--<uncorrect-tag/>-->
</medicins>

=== Foltrex/XML/src/test/resources/medicins.xml
<?xml version="1.0" encoding="UTF-8"?>
<medicins xmlns="http://www.epamcourses.by/medicins"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.epamcourses.by/medicins  medicationsSchema.xsd ">

    <heart-medicine id="medicine290">
        <name>bisoprolol</name>
        <group>beta-blocant</group>
        <analogs>
            <analog>concor</analog>
            <analog>bicard</analog>
        </analogs>
        <versions>
            <version>
                <version-name>PILLS</version-name>
                <pharm>Lekpharm</pharm>
                <certificate>
                    <number>N83bs90vb32</number>
                    <issue-date>2021-12-05</issue-date>
                    <expiry-date>2023-12-05</expiry-date>
                </certificate>
                <package>
                    <type>CARDBOARD BOX</type>
                    <capacity>28</capacity>
                    <price>16</price>
                </package>
                <dosage>
                    <dose>5</dose>
                    <medication-interval>12</medication-interval>
                </dosage>
            </version>
        </versions>
    </heart-medicine>

    <vascular-medicine id="medicine902">
        <name>piracetam</name>
        <group>nootropics</group>
        <analogs>
            <analog>lucetam</analog>
            <analog>macsotropil</analog>
        </analogs>
        <versions>
            <version>
                <version-name>CAPSULES</version-name>
                <pharm>Egis Pharmaceutical</pharm>
                <certificate>
                    <number>bUI82kd5ti</number>
                    <issue-date>2021-12-07</issue-date>
                    <expiry-date>2023-12-07</expiry-date>
                </certificate>
                <package>
                    <type>BLISTER</type>
                    <capacity>10</capacity>
                    <price>7</price>
                </package>
                <dosage>
                    <dose>400</dose>
                    <medication-interval>6</medication-interval>
                </dosage>
            </version>
            <version>
                <version-name>SOLUTION</version-name>
                <pharm>Meness</pharm>
                <certificate>
                    <number>T9nkjSn93</number>
                    <issue-date>2021-11-17</issue-date>
                    <expiry-date>2023-11-17</expiry-date>
                </certificate>
                <package>
                    <type>BOTTLE</type>
                    <capacity>120</capacity>
                    <price>8</price>
                </package>
                <dosage>
                    <dose>2333</dose>
                    <medication-interval>6</medication-interval>
                </dosage>
            </version>
            <version>
                <version-name>PILLS</version-name>
                <pharm>TOGOS</pharm>
                <certificate>
                    <number>BI1bksJHI</number>
                    <issue-date>2021-10-27</issue-date>
                    <expiry-date>2023-10-27</expiry-date>
                </certificate>
                <package>
                    <type>CARDBOARD BOX</type>
                    <capacity>10</capacity>
                    <price>10</price>
                </package>
                <dosage>
                    <dose>200</dose>
                    <medication-interval>6</medication-interval>
                </dosage>
            </version>
        </versions>
    </vascular-medicine>
</medicins>
